### ISSUE TITLE
Bug in setTemp/

### ISSUE THREAD

**Issue by delfinof** [danny-source/Arduino_DY_IRDaikin#1]
In file 
   IRdaikin.cpp

in the "setTemp" function I read the following if:
    if (temp >= 18 && temp>=32)
    {
        daikin[14] = (temp)*2;
        daikinController_checksum();
    }
I guess the second condition should be "<=32", isn't it? (it's winter and I am not brave enough to start the cooling ;)

**Comment by danny-source** [comment]
You are right, remote control temp is 18~32
if (temp >= 18 && temp<=32)
{
daikin[14] = (temp)*2;
daikinController_checksum();
}

it has updated
