### ISSUE TITLE
Arduino Nano

### ISSUE THREAD

**Issue by Veeramk** [danny-source/Arduino_DY_IRDaikin#10]
Just wanted to know whether this works on Arduino nano??

**Comment by danny-source** [comment]
yes,but 16Mhz version i was tried

**Comment by Veeramk** [comment]
pretty newbie to all this I have this ir module
https://robu.in/wp-content/uploads/2019/10/Grove-Infrared-Emitter-User-Manual.pdf
have connected 
vcc to 5v
gnd to gnd
tx to D3


My AC remote is BRC4M150W. 
Have uploaded BRCPowerOnOff.ino to Arduino nano. 
But still doesn't work. Thanks in advance!!

**Comment by danny-source** [comment]
I have no BRC4M150W to try, maybe format is different
