### ISSUE TITLE
Could you please explain what the "SOFT Pinout" means?

### ISSUE THREAD

**Issue by foreverlong** [danny-source/Arduino_DY_IRDaikin#13]
Thank you for your project. Today I successfuly conntrol my air conditioner by Arduino Uno. But I'd like to use esp8266 to put in my local web. I noticed that in this project, ESP8266 is under the "SOFT Pinout". Could you please explain what the "SOFT Pinout" means? Why there are two pins needed? When I use Uno, Pin3 is enough. Please tell me why. Thank you! Best wish for you.

**Comment by foreverlong** [comment]
Is this project suit for esp01? If it can, in esp01, can i use RX pin? Like this picture shows:
![image](https://user-images.githubusercontent.com/43675453/170823059-ad4a8345-546a-4f2f-a4cf-ab67e3878125.png)
![image](https://user-images.githubusercontent.com/43675453/170823085-7090a0e7-153a-439b-841a-7b1b411cc3ca.png)

**Comment by danny-source** [comment]
Soft Pin is soft to simulation signal , you need assign pin to simulate
