### ISSUE TITLE
DYIRDaikinBRC.cpp library has an error

### ISSUE THREAD

**Issue by gigi1956** [danny-source/Arduino_DY_IRDaikin#16]
Good Morning,
I'm trying to use the library DYIRDaikin.h to control a Daikin split, but when I compile the sketch I obtain an error at line 112 of the DYIRDaikinBRC.cpp library. 
The error says:
-------------------
C:\....my_path\libraries\DYIRDaikin\DYIRDaikinBRC.cpp: In member function 'uint8_t DYIRDaikinBRC::checksum()':
C:\....my_path\libraries\DYIRDaikin\DYIRDaikinBRC.cpp:112:1: error: no return statement in function returning non-void [-Werror=return-type]
  112 | }
      | ^
------------------
I'm using a wemos d1 mini, core esp 3.1.2, IDE 1.8.19

How can I solve this issue?
Thank you in advance for your help
gigi (my name)

**Comment by danny-source** [comment]
slove by commit id "a18c63714b2198db958a65d138c7ce887b9be906".
