### ISSUE TITLE
Help in schematic 

### ISSUE THREAD

**Issue by soloam** [danny-source/Arduino_DY_IRDaikin#2]
Can You clarify the schematic on the UNO? Part Numbers of the components? Type of led etc.

Thank You

**Comment by molomax** [comment]
Hi soloam,
in my project I'm using these parts:
- one common IR led (sender) 5mm 850nm 1.5V (or 940nm, depends on the receiver)
- one PN 2222A transistor (check the pinout order)
- one 800 ohm resistor between Arduino UNO and the transistor. NOTE: My configuration is not the same suggested by Danny. Anyway you can check the color code of the resistors shown in the Arduino_UNO_IR_Transmit.png picture. 

The transistor is used to drive the IR led (transmit the impulses) as a switch on/off. The led is powered by 5v output of Arduino UNO.

In my case for my project I'm using an external 5 volt supply (as output) to drive the IR led and it is enough for me.

I've not the right skills to give you the best solution but this is the result of my little experience. So you could wait for the official answer of Danny.

Anyway I hope this will help you.

Regards,
Lomax

**Comment by danny-source** [comment]
> 
> 
> Can You clarify the schematic on the UNO? Part Numbers of the components? Type of led etc.
> 
> Thank You

refer this link:
https://www.analysir.com/blog/2015/10/12/backdoor-upwm-hack-on-arduino-for-infrared-signals-using-uart/
