### ISSUE TITLE
Weekly timers scheduler

### ISSUE THREAD

**Issue by molomax** [danny-source/Arduino_DY_IRDaikin#3]
Hi Danny,
first of all thank you for your great job.
I'm using Arduino UNO and an ARC ir remote model for Daikin.
I would like to understand how to define and turn on (and off) the weekly scheduler.

In this case I'm using the dump and the decode methods but I don't know how to manage or repeat the dumped packets.

At this moment the easiest way could be:
Repeat the sequence of received packets (containing the desired scheduler configuration) and send it with the sendCommand method, but I don't know how do it and if it is the right way.

Here a sample of weekly ON with a 7days scheduler (I've captured it by pressing the “weekly” button of the ARC ir remote. NOTE: The weekly program was already configured):

```
wake
=Decoded=
scount:2
bytes:26
pcount:0
plength:3
--
11-DA-27-00-86-03-00-1E-24-9E-00-1E-00-1E-00-1E-24-9E-00-1E-00-1E-00-1E-37-28-
--

28-28 CRC OK
=PSP=
=Decoded=
scount:420
bytes:26
pcount:1
plength:3
--
11-DA-27-00-C6-01-24-9E-33-5E-00-9E-00-1E-24-9E-00-1E-00-1E-00-1E-24-9E-00-C6-
--

C6-C6 CRC OK
=PSP=
=Decoded=
scount:420
bytes:26
pcount:2
plength:3
--
11-DA-27-00-C6-02-1E-00-1E-00-1E-24-9E-00-1E-00-1E-00-1E-24-9E-00-1E-00-1E-4E-
--

4E-4E CRC OK
=PSP=
=Decoded=
scount:420
bytes:26
pcount:3
plength:3
--
11-DA-27-00-86-03-00-1E-24-9E-00-1E-00-1E-00-1E-24-9E-00-1E-00-1E-00-1E-B7-A8-
--

A8-A8 CRC OK
=data packet=

===
```

I can notice that command is composed by 3 (or 4?) packets and each packet contains part of the full command. The full command contains the 7 days parts (in fact I can see 7 segments containing the 24 hex code). Each segment should represent the daily program\timer event.

The desired goal is:
Create a scheduler for the weekly program: Set the specific timer for each day and turn on and off the weekly scheduler.

Can you help me to obtain this task, please? Could you add this feature to your code?

I will glad to test it and send you my feedbacks.

Thank you in advance.

Regards,
Lomax

**Comment by molomax** [comment]
Hi,
I've changed my original idea. In fact I can turn on and off the Daikin or set any common command\function through Arduino and a DS3231 module. In this way I can schedule desired actions and send related command to Daikin when it is the right time.

Lomax

**Comment by danny-source** [comment]
> 
> 
> Hi,
> I've changed my original idea. In fact I can turn on and off the Daikin or set any common command\function through Arduino and a DS3231 module. In this way I can schedule desired actions and send related command to Daikin when it is the right time.
> 
> Lomax

thx you report.
i have one daikin model,but daikin timer set base on model by model.
