### ISSUE TITLE
New user

### ISSUE THREAD

**Issue by PaskoMoto** [danny-source/Arduino_DY_IRDaikin#5]
Hi.
I just started using this software and wanted to say thank you.
So far I managed to use the decoder. If it helps, the remote I am testing is model ARC433A50.
As soon as I manage to build the emission circuit I'll also try with a split.
Best regards.

**Comment by PaskoMoto** [comment]
Hi.
I finally managed to build a transmitter circuit that works nicely with this software. I've been reading the software and I have a pair of questions to ask:
1.- What's the difference between Swing and SwingLR? My remote only shows a key named 'swing' associated to a function that can be turned on/off. Maybe LR stands for 'Low-Rate'? **edit: ok I think I got it: It means horizontal (left-right) swing**

2.- I've also seen timerOn / timerOff / timerOnValue / timerOffValue variables in the decoding part of DYIRDaikin.cpp, but not in the sending/transmitting part. As far as I know these timers are expresed in decimal minutes from/after the hour stored in the actual remote:
Is it planned to include these timers in the code in the near future ?

Best regards.

**Comment by danny-source** [comment]
> 
> 
> Hi.
> I finally managed to build a transmitter circuit that works nicely with this software. I've been reading the software and I have a pair of questions to ask:
> 1.- What's the difference between Swing and SwingLR? My remote only shows a key named 'swing' associated to a function that can be turned on/off. Maybe LR stands for 'Low-Rate'? **edit: ok I think I got it: It means horizontal (left-right) swing**
> 
> 2.- I've also seen timerOn / timerOff / timerOnValue / timerOffValue variables in the decoding part of DYIRDaikin.cpp, but not in the sending/transmitting part. As far as I know these timers are expresed in decimal minutes from/after the hour stored in the actual remote:
> Is it planned to include these timers in the code in the near future ?
> 
> Best regards.
1.other model have swing for horizontal.
2.timeOn/Offvariables only for testing,i don't complate for sending.

**Comment by PaskoMoto** [comment]
Hi.
Thank you for your answers. I'll have a look at the code and see if I can implement it.
Regards.
