### ISSUE TITLE
Temperature range

### ISSUE THREAD

**Issue by bent2517** [danny-source/Arduino_DY_IRDaikin#7]
With the Arduino I can only set a temperature down to 18 degrees, with the remote I can set it down to 10. How do I set it lower with the Arduino?

**Comment by danny-source** [comment]
no, 18 degree is limit by daikin machine.

**Comment by Antebzh** [comment]
Hi,
10°C heat mode on remote for the frost protection.

**Comment by bent2517** [comment]
With the remote the limits are 10-30 degrees.
If I change DYIRDaikin.cpp third line to to "if (temp >= 12 && temp<=32)"
Would that work?
Or is there a command for frost protection?

1. void DYIRDaikin::setTemp(uint8_t temp)
2. {
3. if (temp >= 18 && temp<=32)
4. {
5. daikin[14] = (temp)*2;
6. checksum();
7. }
8. }

**Comment by danny-source** [comment]
> 
> 
> With the remote the limits are 10-30 degrees.
> If I change DYIRDaikin.cpp third line to to "if (temp >= 12 && temp<=32)"
> Would that work?
> Or is there a command for frost protection?
> 
>     1. void DYIRDaikin::setTemp(uint8_t temp)
> 
>     2. {
> 
>     3. if (temp >= 18 && temp<=32)
> 
>     4. {
> 
>     5. daikin[14] = (temp)*2;
> 
>     6. checksum();
> 
>     7. }
> 
>     8. }

if your machine is support for 10-30 degrees, yes!
