### ISSUE TITLE
Check sum error will decoding IR codes from Daikin ARC480A8 remote

### ISSUE THREAD

**Issue by sisimomo** [danny-source/Arduino_DY_IRDaikin#9]
Hello,

First, I would like to say thank you for your excellent library. I have already been able to make my air conditioning smart using your library. Now the next step is to synchronize the state displayed on my automation hub (Hassio) and the actual state of AC. To do this, I wanted to rely on the "Bridge" example. But unfortunately I have some difficulty getting it to work. Here is my situation.

I get an error code when I try to decode the IR codes sent by my remote "ARC480A8".

Here is my wiring diagram:

<img src="https://user-images.githubusercontent.com/27745204/109598114-9d984180-7ae6-11eb-8de2-a4e90566e3dd.png" height="500" />

To do this I used the Bridge example. The only thing I have to change is the pin numbers. As a Board, I use an Uno R3.

For this example, I looped between these two commands:
<div style="display: flex">
<img src="https://user-images.githubusercontent.com/27745204/109596178-b7845500-7ae3-11eb-81f8-5aa7d0a88078.jpg" height="200" />
<img src="https://user-images.githubusercontent.com/27745204/109596181-b94e1880-7ae3-11eb-873f-a40f3c5504bb.jpg" height="200" />
</div>

Here are the console errors when I send the IR codes using the remote:

```
Daikin Bridge Start!
wake
=Timeout=2=restart
=Decoded=
scount:308
bytes:19
pcount:1
plength:2
--
11-DA-27-00-00-31-2C-00-5F-00-00-00-00-00-00-C5-00-00-93-
--

93-93 CRC OK
=PSP=
detect packet is timeout,restart
wake
=Decoded=
scount:2
bytes:1
pcount:0
plength:2
--
11-
--

00-11 CRC ERR
-check sum error-restart
=Decoded=
scount:308
bytes:19
pcount:1
plength:3
--
11-DA-27-00-00-31-2A-00-5F-00-00-00-00-00-00-C5-00-00-91-
--

91-91 CRC OK
=PSP=
detect packet is timeout,restart
wake
=Timeout=2=restart
=Decoded=
scount:308
bytes:19
pcount:1
plength:2
--
11-DA-27-00-00-31-2C-00-5F-00-00-00-00-00-00-C5-00-00-93-
--

93-93 CRC OK
=PSP=
detect packet is timeout,restart
=Timeout=2=restart
=Decoded=
scount:308
bytes:19
pcount:1
plength:2
--
15-DA-27-00-00-31-2A-00-5F-00-00-00-00-00-00-C5-00-00-91-
--

95-91 CRC ERR
-check sum error-restart
wake
=Timeout=2=restart
=Decoded=
scount:308
bytes:19
pcount:1
plength:2
--
11-DA-27-00-00-31-2C-00-5F-00-00-00-00-00-00-C5-00-00-93-
--

93-93 CRC OK
=PSP=
detect packet is timeout,restart
```
So, my question is the following:

Why am I getting this error code, and how do I avoid the error in the future?

Thanks, and don't hesitate if you need more details.

**Comment by iv1zz** [comment]
Same problem with ARC480A33.

**Comment by danny-source** [comment]
May be protocol is not fit, i don't have ARC480A8 for testing, sorry
